version: "3"

services:
  web:
    platform: linux/amd64
    container_name: web
    image: bhj-monorepo-web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - app_network
  docs:
    platform: linux/amd64
    container_name: docs
    image: bhj-monorepo-docs:latest
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    restart: always
    ports:
      - 3000:3000
    # networks:
    #   - app_network
# Define a network, which allows containers to communicate with each other, by using their container name as a hostname
# networks:
#   app_network:
#     external: true
