name: 프론트엔드 놀이터

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# Job 설정
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [8]

    steps:
      - name: 소스코드 체크아웃 # Repo checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: pnpm ${{ matrix.pnpm-version }} 설치
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Node.js ${{ matrix.node-version }} 설치
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: pnpm 저장 디렉토리 가져오기
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: pnpm 캐시 설정
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 의존성 설치
        run: pnpm install

      - name: 프로젝트 빌드 테스트
        run: pnpm build
