name: "[CD] 프로젝트 배포" # Workflow 이름

on:
  push:
    branches: ["main"] # main 브랜치에 push가 일어날 때만 workflow가 실행됨

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_DOCS_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}

jobs:
  changes:
    name: 변경된 파일 확인
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'apps/docs/**'

  deploy:
    name: 프로젝트 배포 스텝
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 현재 커밋 체크아웃 (${{ github.sha }})
        uses: actions/checkout@v4

      - name: Vercel CLI 설치
        run: yarn add -w vercel@latest

      - name: Vercel 원격 환경에서 환경 변수 및 프로젝트 설정을 가져오기
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 빌드
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 배포
        run: vercel deploy --prebuilt --prod  --token=${{ secrets.VERCEL_TOKEN }}
