name: "[CD] 프로젝트 배포" # Workflow 이름

on:
  push:
    branches: ["main"] # main 브랜치에 push가 일어날 때만 workflow가 실행됨

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_WEB_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID }}

jobs:
  changes:
    name: 변경된 파일 확인
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      web: ${{ steps.filter.outputs.web }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
            packages:
              - 'packages/**'

  deploy:
    name: 프로젝트 배포 스텝
    needs: changes
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [8]
    if: ${{ needs.changes.outputs.web == 'true' || needs.changes.outputs.packages == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 현재 커밋 체크아웃 (${{ github.sha }})
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: pnpm ${{ matrix.pnpm-version }} 설치
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Node.js ${{ matrix.node-version }} 설치
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Vercel CLI 설치
        run: pnpm add -w vercel@latest

      - name: Vercel 원격 환경에서 환경 변수 및 프로젝트 설정을 가져오기
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 빌드
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 프로젝트 배포
        run: vercel deploy --prebuilt --prod  --token=${{ secrets.VERCEL_TOKEN }}
